# Generated by Django 4.2.1 on 2023-06-30 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpostingan',
            name='waktuPosting',
        ),
        migrations.AddField(
            model_name='modelpostingan',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelpostingan',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='modelpostingan',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
